version: "3.3"

services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    command: "yarn test"
    volumes:
      - ./tests:/app/tests
      - ./test-results:/app/test-results
      - ./playwright-report:/app/playwright-report